### ISSUE TITLE
Version 1.0 Roadmap

### ISSUE THREAD

**Issue by kazenshi** [kazenshi/DeltaLib#1]
### Summary
This GitHub issue is to serve as a basic v1.0 roadmap. As such it will be continually updated.

### v0.1 Goals
- [x] Calculate signatures for an input stream
- [ ] Create a model for representing signatures
- [ ] Create unit tests to validate correctness of functionality

### v0.2 Goals
- [ ] Calculate deltas between two files
- [ ] Create a model for representing deltas

### v0.3 Goals
- [ ] Patch an input stream with a delta

### v1.0
- [ ] Benchmark performance
