### ISSUE TITLE
Calculate deltas between 2 files

### ISSUE THREAD

**Issue by kazenshi** [kazenshi/DeltaLib#2]
### User Requirement
As a user, I would like to be able to calculate the binary differences between 2 files so that I can encrypt only the blocks of data that actually changed without re-encrypting the whole file again.

### Tasks
- [x] Create the functionality to calculate binary diffs
  - [x] Research how others are performing binary diffs
  - [x] Apply the rsync algorithm (if it makes sense to after the above step)
- [ ] Create a serializable model to represent deltas programmatically
  - [ ] Determine the properties to reveal about a delta.
  - [ ] Utilize C# 9 records if appropriate.
